GetLineCoordinate_1:
  ros__parameters:
    black_hue_min: 0
    black_hue_max: 180
    black_saturation_min: 0
    black_saturation_max: 255
    black_value_min: 0
    black_value_max: 80
    search_top: 265
    search_bot: 331
    search_top1: 415
    search_bot1: 480