GetLineCoordinate_2:
  ros__parameters:
    # 重要 BOOL 值
    linkage_mode: false                    # 是否开始联动模式
    start_avoid_time: 2.7
    # 寻线参数
    follow_linear_speed: 0.35
    speed_scaling_factor: 0.02
    speed_scaling_max_output: 0.08
    # 跟踪参数
    confidence_threshold: 0.7
    trace_linear_speed: 0.2
    # 避障参数
    avoid_angular_ratio: -0.848
    avoid_linear_speed: 0.55
    avoid_time_1: 1.05
    avoid_time_2: 2.25
    avoid_time_3: 0.000001
    avoid_time_4: 0.85
    avoid_time_5: 1.85
    avoid_time_6: 0.000005
    avoid_ratio_coefficient_1: 0.40
    avoid_ratio_coefficient_2: 1.0
    avoid_ratio_coefficient_3: 0.96
    bottom_threshold: 213
    safe_distance: 0
    obstacle_area_threshold: 50
    # PID 参数
    P_param: 0.00395
    I_param: 0.0
    D_param: 0.00415
    target_param: 0.0
    integral_limit_param: 0.0008
    max_out_param: 1.5
